### ISSUE TITLE
how do I read .fdd & .fdl files with this library

### ISSUE THREAD

**Issue by kolte** [JohnDeere/SampleData#2]
Hi,

I have been trying to find it and noticed that those are not decoding, not sure if I need to install any extra plugins for it?

Can you please help/guide me in right direction?

Thanks
Girish

**Comment by tshearouse** [comment]
Hi Girish, you will need our ADAPT plugins. There is sample code at https://github.com/JohnDeere/ADAPT-Sample-App that has examples of how to use ADAPT. Our plugins are not open source, but you can license a copy free: https://developer.deere.com/#!welcome&doc=offlineSDK.htm

Another option is to use our web API's to pull pre-processed data so you don't have to deal with file formats: https://developer.deere.com/#!documentation&doc=myjohndeere%2FfieldOperations.htm
